
wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [20,20,42, 64,64]
    rows: [10, 10, 7, 3, 50]
  refreshInterval: 1
  mods:
        tasks:
          args: ["__showtasks"]
          cmd: "/home/kai/dotfiles/bin/agenda.sh"
          enabled: true
          position:
            top: 0
            left: 0
            height: 2
            width: 3
          refreshInterval: 10
          title: "Todo"
          type: cmdrunner
        calendar:
          args: ["__showcal"]
          cmd: "/home/kai/dotfiles/bin/agenda.sh"
          enabled: true
          position:
            top: 0
            left: 3
            height: 1
            width: 1
          refreshInterval: 60
          title: "Calendar"
          type: cmdrunner
        mails:
          args: ["__showmail"]
          cmd: "/home/kai/dotfiles/bin/agenda.sh"
          enabled: true
          position:
            top: 2
            left: 0
            height: 1
            width: 1
          refreshInterval: 60
          title: "Mails"
          type: cmdrunner
        unsaved:
          args: ["__showunsavedlist"]
          cmd: "/home/kai/dotfiles/bin/agenda.sh"
          enabled: true
          position:
            top: 3
            left: 0
            height: 1
            width: 1
          refreshInterval: 3
          title: "Unsaved Notes"
          type: cmdrunner
        github:
          args: ["wtf"]
          cmd: "/home/kai/dotfiles/bin/githelper"
          enabled: true
          position:
            top: 1
            left: 3
            height: 1
            width: 1
          refreshInterval: 300
          title: "Github"
          type: cmdrunner
