
wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [20,20,42, 64,64]
    rows: [15, 8, 3, 50]
  refreshInterval: 10
  term: "xterm-256color"
  mods:
        tasks:
          args: ["__showtasks"]
          cmd: "/home/kai/dotfiles/bin/agenda.sh"
          enabled: true
          position:
            top: 0
            left: 0
            height: 1
            width: 3
          refreshInterval: 10
          title: "Todo"
          focusable: false
          type: cmdrunner
        calendar:
          args: ["__showcal"]
          cmd: "/home/kai/dotfiles/bin/agenda.sh"
          enabled: true
          position:
            top: 0
            left: 3
            height: 1
            width: 1
          refreshInterval: 60
          title: "Calendar"
          focusable: false
          type: cmdrunner
        mails:
          args: ["__showmail"]
          cmd: "/home/kai/dotfiles/bin/agenda.sh"
          enabled: true
          position:
            top: 1
            left: 0
            height: 1
            width: 1
          refreshInterval: 60
          focusable: false
          title: "Mails"
          type: cmdrunner
        today:
          args: []
          cmd: "/home/kai/dotfiles/bin/today"
          enabled: true
          position:
            top: 1
            left: 1
            height: 3
            width: 2
          refreshInterval: 5
          title: "Plan für heute"
          focusable: false
          type: cmdrunner
        unsaved:
          args: ["__showunsavedlist"]
          cmd: "/home/kai/dotfiles/bin/agenda.sh"
          enabled: true
          position:
            top: 2
            left: 0
            height: 1
            width: 1
          refreshInterval: 10
          title: "Unsaved Notes"
          focusable: false
          type: cmdrunner
        daily:
          args: []
          cmd: "/home/kai/dotfiles/bin/dailytasks"
          enabled: true
          position:
            top: 3
            left: 0
            height: 1
            width: 1
          refreshInterval: 10
          title: "Daily tasks"
          focusable: false
          type: cmdrunner
        github:
          args: ["wtf"]
          cmd: "/home/kai/dotfiles/bin/githelper"
          enabled: false
          position:
            top: 1
            left: 3
            height: 1
            width: 1
          refreshInterval: 300
          title: "Github"
          tail: false
          maxLines: 7
          focusable: false
          type: cmdrunner
        timew:
          args: []
          cmd: "/home/kai/dotfiles/bin/timew-wtf"
          enabled: true
          position:
            top: 1
            left: 3
            height: 3
            width: 1
          refreshInterval: 10
          title: "Time Tracking"
          tail: false
          maxLines: 7
          focusable: false
          type: cmdrunner
        bahn:
          args: []
          cmd: "/home/kai/bin/bahn.sh"
          enabled: false
          position:
            top: 2
            left: 3
            height: 3
            width: 1
          refreshInterval: 300
          title: "Bahn"
          focusable: false
          type: cmdrunner
